[supabase]
url = "https://unvvurusxzctyvzlbtew.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVudnZ1cnVzeHpjdHl2emxidGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5ODQzNTAsImV4cCI6MjA5MTU2MDM1MH0.GMy4OsdZV-2WEbVpUdxcivTF2GIzWmocq_03TXRL-Gg"

[gemini]
api_key = "AIzaSyCHA1TP6CmbOV8HvDycjmXp6dS9qel7sPw"
